<?php
require_once "tableModule.php";
class Groups extends TableModule
{
    protected function getTableName(): string
    {
        return "groups";
    }
    public function Create($fields)
    {
        parent::Create($fields); // TODO: Change the autogenerated stub
    }
    public function Read():array
    {
        return parent::Read(); // TODO: Change the autogenerated stub
    }
    public function Update($fields)
    {
        parent::Update($fields); // TODO: Change the autogenerated stub
    }
    public function Delete($id)
    {
        parent::Delete($id); // TODO: Change the autogenerated stub
    }
    public function exists($id): bool
    {
        return parent::exists($id); // TODO: Change the autogenerated stub
    }
    public function lastID()
    {
        return parent::lastID(); // TODO: Change the autogenerated stub
    }
    public function GetList($fields)
    {
        return parent::GetList($fields); // TODO: Change the autogenerated stub
    }
}